[target.x86_64-linux-gnu-gcc]
linker = "x86_64-linux-gnu-gcc"
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-static-libgcc"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-static-libgcc"]
